name: tasking
description: A new Flutter project.

version: 2.0.6+15

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.4.0
  flutter_markdown: ^0.6.9
  flutter_native_splash: ^2.0.4
  flutter_picker: ^2.0.3
  flutter_riverpod: ^1.0.3
  intl: ^0.17.0
  path: ^1.8.0
  sqflite: ^2.0.2
  timezone: ^0.8.0
  tuple: ^2.0.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  sqflite_common_ffi: ^2.1.0+2

flutter:
  # matrial design
  uses-material-design: true
  # asset
  assets:
    - .env

flutter_icons:
  ios: true
  android: true
  image_path_ios: 'asset/icon/ios/icon-1024.png'
  image_path_android: 'asset/icon/android/icon-512.png'

flutter_native_splash:
  image: 'asset/icon/hibitask.png'
  color: '4CAF50'
